week1_vinayak
IRIS-NITK/IRIS-RoR-Bootcamp-2021 pull request #18
Opened 2022-01-28 15:25 UTC by Vinayak-Cruzer

Snap of HTML Page
![html_snap_iris](https://user-images.githubusercontent.com/97468210/151573547-54a376e3-d952-4a34-a45d-5f0064b6a958.PNG)

2022-01-28 18:23 UTC, Vinayak-Cruzer reviewed
changing to return  from puts inside the function armstrong_number(n)

2022-02-01 12:22 UTC, raosush requested changes
Assignment completed, but you could remove the `gets ` call to get the checks passing

2022-02-01 12:22 UTC, raosush commented on week1/armstrong.rb
> +  end
Ruby's USP is it's elegance and optimisations for programmer's happiness 🙂
For `pow`, you can just do:
```ruby
x**t
```
Which is equivalent to x^t

2022-02-01 12:22 UTC, raosush commented on week1/armstrong.rb
> +    end
Number of digits is easy to find:
```ruby
total_digits = num.digits
```

2022-02-01 12:22 UTC, raosush commented on week1/armstrong.rb
> +    i=1
Maybe just use `n>0` condition

2022-02-01 12:22 UTC, raosush commented on week1/armstrong.rb
> +  n=gets.chomp().to_i
Our testing script directly invokes the function. This is unnecessary and also the reason for the check failing

2022-02-13 04:30 UTC, closed without merging