Code to check for armstrong numbers
IRIS-NITK/IRIS-RoR-Bootcamp-2021 pull request #3
Opened 2022-01-26 09:15 UTC by Akarsh-dundun

2022-02-01 14:18 UTC, raosush commented on week1/armstrong.rb
> +        return false
```suggestion
    if sum == n
        return true
    else
        return false
    end
```
Syntax error -> `if` block should have an ending `end`

2022-02-03 11:11 UTC, gaurang2001 requested changes

2022-02-03 11:11 UTC, gaurang2001 commented on week1/armstrong.rb
> +            sum += i**3
the problem statement asks for sum of digits raised to number of digits in the number. So this `3` should be replaced by `l.length` (`sum += i**l.length`). make this one change and push again

2022-02-04 15:49 UTC, gaurang2001 approved these changes

2022-02-04 15:50 UTC, gaurang2001 commented
You've completed the assignment. Good Job!! 🎉

2022-02-04 15:50 UTC, closed without merging

2022-02-04 16:23 UTC, Akarsh-dundun commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
-->Good Evening Gaurang,    Just writing to apologize for the really ignorant submission of this weeks activity. I will try to tone down on the errors going forward RegardsAkarsh Gupta Sent from Mail for Windows From: Gaurang VelingkarSent: 04 February 2022 21:20To: IRIS-NITK/IRIS-RoR-Bootcamp-2021Cc: Akarsh Gupta; AuthorSubject: Re: [IRIS-NITK/IRIS-RoR-Bootcamp-2021] Code to check for armstrong numbers (PR #3) Closed #3.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***> 